services:
  # Ansibleの実行環境
  ansible-bastion:
    build:
      context: .
      dockerfile: ./ansible_bastion/Dockerfile
    privileged: true
    volumes:
      - ../:/workspace
    tty: true
    depends_on:
      - ansible-target
    networks:
      - lab-net

  # Ansibleの被実行環境
  ansible-target:
    build:
      context: .
      dockerfile: ./ansible_target/Dockerfile
    privileged: true
    tty: true
    networks:
      - lab-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker outside of Dockerのためのボリュームマウント

networks:
  lab-net:
    driver: bridge
