services:
  ansible-bastion:
    build:
      context: .
      dockerfile: ./ansible_bastion/Dockerfile
    privileged: true
    volumes:
      - ../:/workspace
      - ../keys:/shared/ssh
    tty: true
    depends_on:
      - ansible-target
    networks:
      - lab-net

  ansible-target:
    build:
      context: .
      dockerfile: ./ansible_target/Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../keys:/shared/ssh
    tty: true
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge

volumes:
  ssh-keys:
